### ISSUE TITLE
switch to rich

### ISSUE THREAD

**Issue by datawhores** [datawhores/ofscraper#16]
https://rich.readthedocs.io/en/stable/progress.html
- log output above progress bars

**Comment by Jules-WinnfieldX** [comment]
I've been using rich for my large downloader. One strike against, is it doesn't play well on windows outside of Windows Terminal (which isn't included let alone the default below Win11). 

That being said, it is beautiful. There is a screenshot of my program using it (very similar use case) [here](https://github.com/Jules-WinnfieldX/CyberDropDownloader).

**Comment by datawhores** [comment]
Actually your script is one of the reason why I wanted to switch.
I hoping that it will fix some of the issues that I've been noticing with tqdm 
Like progress bars being pushed down by repeating lines

**Comment by Jules-WinnfieldX** [comment]
It handles stuff like that surprisingly well. I've been really impressed with it's handling of resizing and recovery.

**Comment by datawhores** [comment]
https://github.com/users/datawhores/projects/2

**Comment by Jules-WinnfieldX** [comment]
This project is looking fantastic. Keep up the good work (I didn't know where else to message)
