### ISSUE TITLE
Scraper seems to have trouble if you have a lot of paid content to download

### ISSUE THREAD

**Issue by Kurosaki22** [datawhores/ofscraper#20]
Hi there

I have one model where I have more paid content than usually and it seems like the scraper is having trouble with that and throwing an error at the end without downloading the paid content.

![image](https://user-images.githubusercontent.com/69061840/231831367-3182cd8c-2f55-4af1-b971-b04258700297.png)

**Comment by datawhores** [comment]
Another user mentioned this in the discord
were working on a fix

**Comment by datawhores** [comment]
oh I realize now that it expires after 7 days by default 
I will change it now

**Comment by datawhores** [comment]
This issue should be resolved in the test branch
hoping to release to pip soon
