### ISSUE TITLE
run failed with exception 'Text'

### ISSUE THREAD

**Issue by soulburn74** [datawhores/ofscraper#21]
My first try with this script.
I'm able to download a specific accounts paid content without issue (even though some errors appear during this process).
Main issue I'm having is can't download any of the 'regular' content for this specific account, getting 'text' error: 
![image](https://user-images.githubusercontent.com/61853508/232306741-cb64ca91-5d4f-48a5-9184-ad488b187abc.png)
![image](https://user-images.githubusercontent.com/61853508/232306785-1efe6202-0342-4ee0-98d6-bef8855f2f62.png)

**Comment by soulburn74** [comment]
Upon further investigation (trying other users, this only happens on some (assuming it has to do with how many files are present etc??? but purely a guess with no way of validating that thought).

**Comment by datawhores** [comment]
this issue seems to be resolved with the latest commits

**Comment by TestituclarMass** [comment]
Unfortunately, still not resolved. I am obtaining the issue while trying to scrape the timeline on some accounts.

**Comment by datawhores** [comment]
I pushing the test branch as the main branch
please try that it should be version 1.8
