### ISSUE TITLE
Add retry indicator

### ISSUE THREAD

**Issue by soulburn74** [datawhores/ofscraper#23]
I've been fiddling with all the OF scrapers I could find this weekend,  (had been using DC's forever, but its current problems have me looking elsewhere)........ THIS one, works GREAT, so many choices of how to filter things to get exactly what you want (or exactly what you don't, say a model that 17k posts in their archive that hangs the script). I was able to download all of her content except archive, and then go  about to 'selecting all' again (minus her). so I can pull the trigger on scraping EVERYTHING (i'm sure there will be more models down the list that I have to 'creatively' get around...... But THANKS! This rocks!  IF there is a possiblity to figure out why the script is hanging on this model with such a high amount of posts........even better. But with all the tools available via this script, I can get around it as needed :):)

**Comment by datawhores** [comment]
If it slowing down a little bit then going on then 
1. request are taking a long time, theirs no timeout in the program
or
2. 
 some of the requests are failing.
 
To improve the user experience I added the ability to retry each request a number of times.
Theirs a little time gap between each requests. 

17k is the most I've seen thus far, there is a chance more request are having to go through more then once
