### ISSUE TITLE
Scraper skips pinned posts?

### ISSUE THREAD

**Issue by quirkyjoe** [datawhores/ofscraper#25]
I recently scraped a creator's page, and when done I noticed that the total scraped items differed slightly from the number listed on the creator's OF page.
After digging a bit, I found that three of the four missing items were pinned posts.
I'm not sure if there is a fourth item, and if so, what it is, but it seems like the scraper is failing to find the pinned posts.

**Comment by datawhores** [comment]
This is a weird issue because it should match on the main branch now. Since I did not deduplicate.

But not doing this causes issues. So deduplication is a feature on the test branch. Which will be pushed as a new release soon.

Especially if a model has a lots of posts. Their is a good chance that at least some media has been repeatedly uploaded.

Still you might be correct about pinned post not scraping. 

I can add a feature to only scrape pinned posts. Which will make confirming this easier.

**Comment by datawhores** [comment]
Can you test version 1.80 and select only pinned post

**Comment by Ruthalas** [comment]
I am doing so now and will report back!

**Comment by quirkyjoe** [comment]
I will try it and let you know.

**Comment by quirkyjoe** [comment]
It appears to finding the correct content to download, but is consistently running into these two errors partway through the download, at which point the download starts again, which cycles endlessly:

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'H:\\TEMP\\CREATOR\\Profile\\avatar.part' -> 'H:\\TEMP\\CREATOR\\Profile\\avatar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\src\utils\download.py", line 146, in download
    shutil.move(temp,path_to_file)
  File "C:\Python39\lib\shutil.py", line 821, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'H:\\TEMP\\CREATOR\\Profile\\avatar.part'
```

`etryError[<Future at 0x1f55846d940 state=finished returned tuple>]`

I tried a few target directories (faster drives, etc.) with no change in behavior.

**Comment by datawhores** [comment]
Are you still having this error?

**Comment by quirkyjoe** [comment]
Tried on another machine, and did not have the same issue.
So that seems to be on my end.
I will update regarding the pinned posts once the run is complete.

**Comment by quirkyjoe** [comment]
That seems to work! Thank you.
