### ISSUE TITLE
Files not moving to "save_location"

### ISSUE THREAD

**Issue by deadcode0815** [datawhores/ofscraper#31]
After downloading content the files still remain at C:\Users\insertnamehere\Data\ofscraper and won't move to "save_location"
It would be nice to have even the tempfiles are saved on "save_location" because the size of my c drive is kinda limited.

**Comment by datawhores** [comment]
Are you on 1.87
Run with ofscraper --log debug

and look for the log file in the config location

It should give info on why the files aren't moving
