### ISSUE TITLE
Metadata not being saved in specified location

### ISSUE THREAD

**Issue by ResidentSpaceDragon** [datawhores/ofscraper#33]
I want
```
"metadata":"{model_username}/Metadata",
at the {save_location}
```
I'm getting
```
/home/user/.config/ofscraper/profile/.data/username_modelid/user_data.db
```
 as if it is hard coded to use the users home folder(which i dont want) Am i missing something or does the program only allow metadata to be saved to ~~/.ofscraper?
I am also migrating from DC and would like to keep the db file

**Comment by datawhores** [comment]
Please post your full config

**Comment by ResidentSpaceDragon** [comment]
```
{
    "config": {
        "main_profile": "main_profile",
        "save_location": "/Onlyfans",
        "file_size_limit": 0,
        "dir_format": "{model_username}/{responsetype}/{value}/{date}",
        "file_format": "{filename}.{ext}",
        "textlength": "0",
        "date": "YYYY-MM-DD",
        "metadata":"{model_username}/Metadata",
        "filter": [
            "Images",
            "Audios",
            "Videos"
        ],
        "responsetype": {
            "timeline": "posts",
            "archived": "archived",
            "pinned": "archived",
            "message": "messages",
            "paid": "messages",
            "stories": "stories",
            "highlights": "highlights",
            "profile": "profile"
        }
    }
}
```

**Comment by datawhores** [comment]
/Onlyfans/{model_username}/Metadata

Is what you would want for metadata settings

This is a good reminder to update the wiki
1. It needs to be a full path
2. I can also give an example

**Comment by ResidentSpaceDragon** [comment]
The archive,messages,pinned and timeline json files arent moving to the specified metadata folder,they are in the models ".data" folder in the ~~/.ofscraper folder. The user db however did move and successfully migrated my DC metadata to the custom desination

**Comment by datawhores** [comment]
Those are hardcoded

They are used for cache
I'm going to change them to one file.
They just used to speed up subsequent scrapes
