### ISSUE TITLE
Not scraping all content

### ISSUE THREAD

**Issue by ResidentSpaceDragon** [datawhores/ofscraper#34]
The scraper reports 8223 photos,195 videos and 14 audios which matches the amount shown on the OF profile media tab, however the entire user profile contains less then 6000 files. This is with a fresh folder and scrape

```
{
    "config": {
        "main_profile": "main_profile",
        "save_location": "/Onlyfans",
        "file_size_limit": 0,
        "dir_format": "{model_username}/{responsetype}/{value}/{date}",
        "file_format": "{filename}.{ext}",
        "textlength": "0",
        "date": "YYYY-MM-DD",
        "metadata": "{configpath}/{profile}/.data/{model_username}_{model_id}",
        "filter": [
            "Images",
            "Audios",
            "Videos"
        ],
        "responsetype": {
            "timeline": "posts",
            "archived": "archived",
            "pinned": "archived",
            "message": "messages",
            "paid": "messages",
            "stories": "stories",
            "highlights": "highlights",
            "profile": "profile"
        }
    }
}
```

**Comment by datawhores** [comment]
right now the most likely answer is dupe content.

In a previous version this caused racing issue where when coroutine would block another one. Because they both tried to access the same file name.

**Comment by datawhores** [comment]
right now the most likely answer is dupe content.

In a previous version this caused racing issue where when coroutine would block another one. Because they both tried to access the same file name.

    
Edit

You can get the send the name via discord
I'm added some debugger statement for the different counts
