### ISSUE TITLE
Is this compatible with existing download directories?

### ISSUE THREAD

**Issue by avekifes** [datawhores/ofscraper#35]
I already have a ton of content that I downloaded with the original scraper. If I set this fork to download to the same directory, is that...safe? It's not going to overwrite or delete anything, is it?

**Comment by datawhores** [comment]
delete no
Overwrite yes

The database needs to be filled, and their is no auto migration for the original script. We do offer migration from dc's script.

But we have safety check to make sure downloads are complete before overwriting or writing to disk.

**Comment by avekifes** [comment]
Okay, thanks for clarifying. But on second thought, I think I'll just use a fresh directory just to be safe.

One more thing...does your script have that weird quirk where it tries to download from every model you're subscribed to (or receiving messages from) even when you pick one specific account to download from? DC's script doesn't work at all for me because of this and keeps hanging.

**Comment by datawhores** [comment]
No it will only scrape what you select
There  is a lot of control over this
