### ISSUE TITLE
"textlength" isn't working

### ISSUE THREAD

**Issue by spiderzero3** [datawhores/ofscraper#40]
I have my files formatted as "{date} {text} {media_id}.{ext}" but the "textlength" variable in config.json doesn't seem to be working. I'm not sure if any of the filenames are adhering to the limit.

Running the latest development version on Windows.

**Comment by spiderzero3** [comment]
Just read through the page about command line args and see the explanation (textlength counts number of words, not characters). My bad, closed the issue.

**Comment by datawhores** [comment]
done
